import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const sourceDirs = [
  path.resolve(root, "..", "文章"),
  path.join(root, "content", "posts"),
];
const outputFile = path.join(root, "app", "generated-posts.ts");
const imageManifestFile = path.join(root, "content", "article-images.json");
const imageCatalog = [
  { path: "/images/life-path.png", keywords: ["人生", "選擇", "方向", "改變", "成長", "重新編排", "路", "下一步"] },
  { path: "/images/paper-collage.png", keywords: ["關係", "界線", "溝通", "人際", "家庭", "陪伴", "情緒"] },
  { path: "/images/window-space.png", keywords: ["死亡", "離別", "無常", "告別", "珍惜", "休息", "安靜", "療癒"] },
  { path: "/images/morning-desk.png", keywords: ["忙碌", "工作", "規劃", "習慣", "整理", "節奏", "寫作", "時間", "生活"] },
];

function readImageManifest() {
  if (!fs.existsSync(imageManifestFile)) return {};
  return JSON.parse(fs.readFileSync(imageManifestFile, "utf8"));
}

function chooseImage(fields, content, manifest, usedImages) {
  if (manifest[fields.slug] && !usedImages.has(manifest[fields.slug])) return manifest[fields.slug];

  const searchable = [fields.title, fields.category, fields.excerpt, content].join(" ");
  const available = imageCatalog.filter((image) => !usedImages.has(image.path));
  if (available.length === 0) {
    throw new Error(`${fields.title} 找不到尚未使用的圖片，請在 public/images 新增圖片後再更新。`);
  }

  return available
    .map((image, index) => ({
      image,
      score: image.keywords.reduce((score, keyword) => score + (searchable.includes(keyword) ? 1 : 0), 0),
      index,
    }))
    .sort((a, b) => b.score - a.score || a.index - b.index)[0].image.path;
}

function readFrontmatter(source, fileName) {
  const match = source.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);
  if (!match) throw new Error(`${fileName} 缺少 frontmatter（檔案開頭需要 ---）`);

  const fields = {};
  for (const line of match[1].split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim().replace(/^['"]|['"]$/g, "");
    fields[key] = value;
  }

  const required = ["slug", "category", "categorySlug", "date", "title", "excerpt", "readingTime"];
  for (const key of required) {
    if (!fields[key]) throw new Error(`${fileName} 缺少欄位：${key}`);
  }

  const content = match[2]
    .trim()
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.replace(/[ \t]+$/gm, "").trim())
    .filter(Boolean);

  return { ...fields, content, fileName };
}

const files = sourceDirs.flatMap((sourceDir) => {
  if (!fs.existsSync(sourceDir)) return [];
  return fs.readdirSync(sourceDir)
    .filter((file) => file.endsWith(".md") && file !== "README.md")
    .map((file) => ({ file, sourceDir }));
});

const manifest = readImageManifest();
const uniqueSources = files
  .map(({ file, sourceDir }) => readFrontmatter(fs.readFileSync(path.join(sourceDir, file), "utf8"), file))
  .filter((post, index, all) => all.findIndex((candidate) => candidate.slug === post.slug) === index);

const usedImages = new Set();
const posts = uniqueSources
  .map((post) => {
    const image = post.image || chooseImage(post, post.content.join(" "), manifest, usedImages);
    const imageFile = path.join(root, "public", image.replace(/^\//, ""));
    if (!fs.existsSync(imageFile)) throw new Error(`${post.fileName} 指定的圖片不存在：${image}`);
    if (usedImages.has(image)) throw new Error(`${post.fileName} 使用了重複圖片：${image}`);
    usedImages.add(image);
    manifest[post.slug] = image;
    const { fileName, ...article } = post;
    return { ...article, image };
  })
  .sort((a, b) => b.date.localeCompare(a.date));

fs.writeFileSync(imageManifestFile, `${JSON.stringify(manifest, null, 2)}\n`);

const generated = `// This file is generated by scripts/generate-posts.mjs. Do not edit it directly.\nimport type { Article } from "./data";\n\nexport const articles: Article[] = ${JSON.stringify(posts, null, 2)};\n`;
fs.writeFileSync(outputFile, generated);
console.log(`已產生 ${posts.length} 篇文章：${path.relative(root, outputFile)}`);
